name: 'Hello World'
description: 'Greet someone'
inputs:
  branching-model:  # id of input
    description: 'Branching model of the project'
    required: true
    default: 'gitflow'
  branch:
    description: 'Branch that is running the action'
    required: true
    default: 'develop' 
outputs:
  environment:
    description: "Environment target"
    value: ${{ steps.output_environment.outputs.environment }}
runs:
  using: "composite"
  steps:
    - name: "gitflow - env Prd"
      if: ${{ (inputs.branching-model == 'gitflow') }} 
      run: |
        if [[ "${{ inputs.branch }}" == refs/heads/feature/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/release/* ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/main || "${{ inputs.branch }}" == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        fi
      shell: bash
    - name: "gitflow - Somos Belcorp"
      if: ${{ (inputs.branching-model == 'gitflow') }} 
      run: |
        if [[ "${{ inputs.branch }}" == refs/heads/feature/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/release/* || "${{ inputs.branch }}" == refs/heads/qas ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/main || "${{ inputs.branch }}" == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        fi
      shell: bash
    - id: output_environment
      run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
