name: Iterate JSON Array

description: Iterate through a JSON array and echo the values of each item

inputs:
  json_array:
    description: 'JSON array with items containing "file", "pattern", and "value" fields'
    required: true
    default: '[]'

runs:
  using: "composite"
  steps:
    - name: Parse JSON array
      id: parse_json
      shell: bash
      run: |
        echo "::set-output name=items::${{ inputs.json_array }}"
        echo "${{ inputs.json_array }}" > items.json

    - name: Iterate JSON array and echo values
      shell: bash
      run: |
        ls >> $env:GITHUB_OUTPUT
        cat items.json >> $env:GITHUB_OUTPUT
        items=$(cat items.json)
        for row in $(echo "${items}" | jq -r '.[] | @base64'); do
          _jq() {
            echo ${row} | base64 --decode | jq -r ${1}
          }

          file=$(_jq '.file')
          pattern=$(_jq '.pattern')
          value=$(_jq '.value')

          echo "File: ${file}"  >> $env:GITHUB_OUTPUT
          echo "Pattern: ${pattern}"  >> $env:GITHUB_OUTPUT
          echo "Value: ${value}"  >> $env:GITHUB_OUTPUT
        done

        
