name: 'Hello World'
description: 'Greet someone'
inputs:
  branching-model:  # id of input
    description: 'Branching model of the project'
    required: true
    default: 'gitflow'
  branch-push:
    description: 'Branch that is running the action'
    required: true
    default: 'develop' 
  branch-pr-target:
    description: 'Branch that is target for the pullrequest'
    required: true
    default: '' 
  event:
    description: 'Github action event: push or pull_request'
    required: true
    default: '' 
outputs:
  environment:
    description: "Environment target"
    value: ${{ steps.output_environment.outputs.environment }}
runs:
  using: "composite"
  steps:
    - name: "define branch"
      shell: bash
      run: |
        if [[ "${{inputs.event}}" == push ]]; then
          echo "branch=${{inputs.branch-push}}" >> $GITHUB_ENV
        elif [[ "${{inputs.event}}" == pull_request ]]; then
          echo "branch=${{inputs.branch-pr-target}}" >> $GITHUB_ENV
        fi
    - name: "gitflow - env Prd"
      if: ${{ (inputs.branching-model == 'gitflow') }} 
      run: |
        if [[ $BRANCH == refs/heads/feature/* ||  $BRANCH == refs/heads/feat/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/release/* ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/main || $BRANCH == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        fi
        echo $BRANCH
      shell: bash
    - name: "gitflow - Somos Belcorp"
      if: ${{ (inputs.branching-model == 'gitflow-somosbelcorp') }} 
      run: |
        if [[ $BRANCH == refs/heads/feature/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/release/* || $BRANCH == refs/heads/qas ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/main || $BRANCH == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/revamp ]]; then
          echo "environment=revamp" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/SBGANAQA ]]; then
          echo "environment=SBGANAQA" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/SBEPDQA ]]; then
          echo "environment=SBEPDQA" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/SBUNETEQAMC ]]; then
          echo "environment=SBUNETEQAMC" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/SBBPTQA ]]; then
          echo "environment=SBBPTQA" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/SBTSQA ]]; then
          echo "environment=SBTSQA" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/ppr ]]; then
          echo "environment=PPR" >> $GITHUB_ENV
        elif [[ $BRANCH == refs/heads/pprfix ]]; then
          echo "environment=PPRFIX" >> $GITHUB_ENV
        fi
      shell: bash
    - id: output_environment
      run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
