name: 'Hello World'
description: 'Greet someone'
inputs:
  branching-model:  # id of input
    description: 'Branching model of the project'
    required: true
    default: 'gitflow'
  branch:
    description: 'Branch that is running the action'
    required: true
    default: 'develop' 
outputs:
  environment:
    description: "Environment target"
    value: ${{ steps.output_environment.outputs.environment }}
runs:
  using: "composite"
  steps:
    - name: "gitflow - env Prd"
      if: ${{ (inputs.branching-model == 'gitflow') }} 
      run: |
        if [[ "${{ inputs.branch }}" == refs/heads/feature/* ||  "${{ inputs.branch }}" == refs/heads/feat/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/release/* ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/main || "${{ inputs.branch }}" == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        fi
      shell: bash
    - name: "gitflow - Somos Belcorp"
      if: ${{ (inputs.branching-model == 'gitflow-somosbelcorp') }} 
      run: |
        if [[ "${{ inputs.branch }}" == refs/heads/feature/* ]]; then
          echo "environment=DEVELOP" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/release/* || "${{ inputs.branch }}" == refs/heads/qas ]]; then
          echo "environment=QAS" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/main || "${{ inputs.branch }}" == refs/heads/master ]]; then
          echo "environment=PRD" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/revamp ]]; then
          echo "environment=revamp" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/SBGANAQA ]]; then
          echo "environment=SBGANAQA" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/SBEPDQA ]]; then
          echo "environment=SBEPDQA" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/SBUNETEQAMC ]]; then
          echo "environment=SBUNETEQAMC" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/SBBPTQA ]]; then
          echo "environment=SBBPTQA" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/SBTSQA ]]; then
          echo "environment=SBTSQA" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/ppr ]]; then
          echo "environment=PPR" >> $GITHUB_ENV
        elif [[ "${{ inputs.branch }}" == refs/heads/pprfix ]]; then
          echo "environment=PPRFIX" >> $GITHUB_ENV
        fi
      shell: bash
    - id: output_environment
      run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
