name: 'generateNameBasedPattern'
description: 'Get the name of a service name or task name based on pattern'
inputs:
  name:
    description: 'Name of the componente'
    required: true
    default: ''
  environment:
    description: 'Environment'
    required: true
    default: ''
  index:
    description: 'index or complementary text'
    required: true
    default: ''
  pattern:
    description: 'Pattern to return the name'
    required: true
    default: ''
outputs:
  name:
    description: "Environment target"
    value: ${{ steps.output.outputs.NAME }}
runs:
  using: 'composite'
  steps:
    - name: "gitflow"
      run: |
        if [[ ${{inputs.pattern}} == "NAME-i-ENV" ]]; then
          echo "NAME=${{inputs.name}}-${{inputs.index}}-${{inputs.environment}}" >> $GITHUB_ENV
        elif [[ ${{inputs.pattern}} == "NAME-ENV-i" ]]; then
          echo "NAME=${{inputs.name}}-${{inputs.environment}}-${{inputs.index}}" >> $GITHUB_ENV
        fi
      shell: bash
    - id: output
      run: |
              echo "NAME=$NAME" >> $GITHUB_OUTPUT
              echo "NAME=$NAME"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
