name: 'Get Repository Variable'
description: 'Get the value of a repository variable'
inputs:
  variable-name:
    description: 'Name of the repository variable'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Get Repository Variable Value
      id: get_variable
      run: echo ${{ env[inputs.variable-name] }}
      shell: bash
    - name: Set Output
      shell: bash
      run: echo "value=${{ steps.get_variable.outputs.value }}" >> $GITHUB_ENV
